// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdpKWrDKFfQdQ91w7B93S0C2vxgSlPXA',
    appId: '1:182291980784:web:5ba8e076f0f71d9a64bd35',
    messagingSenderId: '182291980784',
    projectId: 'mreader',
    authDomain: 'mreader.firebaseapp.com',
    databaseURL: 'https://mreader-default-rtdb.firebaseio.com',
    storageBucket: 'mreader.appspot.com',
    measurementId: 'G-NNJT5KV6FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_D1idY9WgDwdx2WEr4Cxdoa2uugP1WA',
    appId: '1:182291980784:android:40179f46ad4b7fbf64bd35',
    messagingSenderId: '182291980784',
    projectId: 'mreader',
    databaseURL: 'https://mreader-default-rtdb.firebaseio.com',
    storageBucket: 'mreader.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0iit16T-6Tvy1_TYCzto28zFVFHGyKEg',
    appId: '1:182291980784:ios:9f15635264bf92f564bd35',
    messagingSenderId: '182291980784',
    projectId: 'mreader',
    databaseURL: 'https://mreader-default-rtdb.firebaseio.com',
    storageBucket: 'mreader.appspot.com',
    androidClientId: '182291980784-04vddbadvb218q6bnkmajkseidni1na5.apps.googleusercontent.com',
    iosClientId: '182291980784-p46dthndmcivir3nqhet6f6pi6ad3bie.apps.googleusercontent.com',
    iosBundleId: 'dev.newquist.mreader',
  );

}